In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("data/archive/imdb_top_1000_cleaned.csv")
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [6]:
df.drop(df[df["Released_Year"] == "PG"].index,inplace=True)

In [7]:
def func(year):
    if year in range(1920,1930):
        return "1920s"
    elif year in range(1930,1940):
        return "1930s"
    elif year in range(1940,1950):
        return "1940s"
    elif year in range(1950,1960):
        return "1950s"
    elif year in range(1960,1970):
        return "1960s"
    elif year in range(1970,1980):
        return "1970s"
    elif year in range(1980,1990):
        return "1980s"
    elif year in range(1990,2000):
        return "1990s"
    elif year in range(2000,2010):
        return "2000s"
    elif year in range(2010,2020):
        return "2010s"
    elif year == 2020:
        return "2020"

# df["Range"] = df["Released_Year"].apply(func)

In [8]:
df["Released_Year"] = pd.to_numeric(df["Released_Year"])
df["range"] = df["Released_Year"].apply(func)

In [9]:
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,range
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",1990s
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",1970s
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",2000s
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",1970s
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",1950s

In [10]:
df.isnull().sum()

Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
range              0
dtype: int64

In [11]:
df.drop(["Certificate","Meta_score","Gross"],axis=1,inplace=True)

In [12]:
df.to_csv("data/archive/final_cleaned.csv",index=False)